local cmd = vim.cmd
local hl = vim.api.nvim_set_hl

cmd('set background=light')
cmd('colorscheme melange')
cmd('hi Normal guibg=NONE')
cmd('hi StatusLine guibg=#f0f0f0 guifg=#444444')
cmd('hi Pmenu guibg=NONE')
cmd('hi CursorLine guibg=#eeeeee')
cmd('hi WinSeparator guifg=#e0e0e0')
--cmd('hi PmenuSel guibg=#ebebeb guifg=#000000')
cmd('hi CmpBorder guifg=#a98a78')
cmd('hi CmpDocBorder guifg=#a98a78')
cmd('hi Comment guifg=#b1a39b')
cmd('hi BufferLineFill guibg=#f0f0f0')
cmd('hi BufferLineBackground guibg=#e2e2e2')
cmd('hi BufferLineNvimTree guibg=NONE guifg=NONE')
cmd('hi BufferLineOffsetSeparator guibg=NONE guifg=#e0e0e0')
--cmd('hi Comment guifg=#aaaaaa')
--
hl(0, 'CmpItemAbbrDeprecated', { bg='NONE', strikethrough=true, fg='#808080' })
hl(0, 'CmpItemAbbrMatch', { bg='NONE', fg='#569CD6' })
hl(0, 'CmpItemAbbrMatchFuzzy', { link='CmpIntemAbbrMatch' })
hl(0, 'CmpItemKindVariable', { bg='NONE', fg='#564AA4' })
hl(0, 'CmpItemKindInterface', { link='CmpItemKindVariable' })
hl(0, 'CmpItemKindText', { link='CmpItemKindVariable' })
hl(0, 'CmpItemKindFunction', { bg='NONE', fg='#bc5c00' })
hl(0, 'CmpItemKindMethod', { link='CmpItemKindFunction' })
hl(0, 'CmpItemKindKeyword', { bg='NONE', fg='#3a684a' })
hl(0, 'CmpItemKindProperty', { link='CmpItemKindKeyword' })
hl(0, 'CmpItemKindUnit', { link='CmpItemKindKeyword' })


-- Bufferline icons
cmd('hi default BufferLineDevIconSvelte guibg=#e2e2e2')
cmd('hi default BufferLineDevIconHs guibg=#e2e2e2')
cmd('hi default BufferLineDevIconGo guibg=#e2e2e2')
cmd('hi default BufferLineDevIconRust guibg=#e2e2e2')
cmd('hi default BufferLineDevIconHtml guibg=#e2e2e2')
cmd('hi default BufferLineDevIconTypeScript guibg=#e2e2e2')
cmd('hi default BufferLineDevIconCss guibg=#e2e2e2')
cmd('hi default BufferLineDevIconJavaScript guibg=#e2e2e2')
